#!/usr/bin/env Rscript
library('crayon')
library('devtools')
library('formatR')

cat(blue("1/5>>>>>>>>>>>>> CLEANING CODE.\n"))
setwd('./memanorm')
tidy_dir(recursive=TRUE,arrow=TRUE)

cat(blue("2/5>>>>>>>>>>>>> DOCUMENTING.\n"))
devtools::document()
setwd('..')

cat(blue("3/5>>>>>>>>>>>>> BUILDING.\n"))
devtools::build('./memanorm',vignettes=TRUE)

cat(blue("4/5>>>>>>>>>>>>> INSTALLING.\n"))
fle = dir()[grepl("gz",dir())]
stopifnot(length(fle)==1)
install.packages(paste('./',fle,sep=""))

cat(blue("5/5>>>>>>>>>>>>> CHECKING.\n"))
devtools::check('./memanorm',cran=TRUE)
